import type { Meat } from '../domain/meat';

export const DEFAULT_MEATS: Meat[] = [
  {
    id: 'picanha',
    nameJa: 'ピッカーニャ',
    nameEn: 'Picanha',
    category: 'beef',
    rarity: 'common',
    satiety: 12,
    flavorText: 'The sweetness of the fat moves your refactor along.',
    effectLabel: 'Focus +1',
  },
  {
    id: 'alcatra',
    nameJa: 'アウカトラ',
    nameEn: 'Alcatra',
    category: 'beef',
    rarity: 'common',
    satiety: 10,
    flavorText: 'Lean strength tightens up your type definitions.',
    effectLabel: 'Design +1',
  },
  {
    id: 'fraldinha',
    nameJa: 'フラウジーニャ',
    nameEn: 'Fraldinha',
    category: 'beef',
    rarity: 'common',
    satiety: 10,
    flavorText: 'A balanced bite that helps you take review comments in stride.',
    effectLabel: 'Review resistance +1',
  },
  {
    id: 'costela',
    nameJa: 'コステーラ',
    nameEn: 'Costela',
    category: 'beef',
    rarity: 'uncommon',
    satiety: 15,
    flavorText: 'A bone-deep flavor that supports your architecture.',
    effectLabel: 'Structure +2',
  },
  {
    id: 'cupim',
    nameJa: 'クッピン',
    nameEn: 'Cupim',
    category: 'beef',
    rarity: 'uncommon',
    satiety: 14,
    flavorText: 'A rich aftertaste lets you face down legacy code.',
    effectLabel: 'Persistence +2',
  },
  {
    id: 'linguica',
    nameJa: 'リングイッサ',
    nameEn: 'Linguica',
    category: 'pork',
    rarity: 'common',
    satiety: 8,
    flavorText: 'Lively spice burns through afternoon drowsiness.',
    effectLabel: 'Refresh +2',
  },
  {
    id: 'coracao',
    nameJa: 'コラソン',
    nameEn: 'Coracao',
    category: 'chicken',
    rarity: 'uncommon',
    satiety: 7,
    flavorText: 'Small but brave — strong against bugs, too.',
    effectLabel: 'Courage +1',
  },
  {
    id: 'frango',
    nameJa: 'フランゴ',
    nameEn: 'Frango',
    category: 'chicken',
    rarity: 'common',
    satiety: 9,
    flavorText: 'A light chicken bite reboots your afternoon.',
    effectLabel: 'Reboot +1',
  },
  {
    id: 'porco',
    nameJa: 'ポルコ',
    nameEn: 'Porco',
    category: 'pork',
    rarity: 'common',
    satiety: 11,
    flavorText: 'A fragrant bite lets you cross off another TODO.',
    effectLabel: 'Throughput +1',
  },
  {
    id: 'cordeiro',
    nameJa: 'ラム',
    nameEn: 'Lamb',
    category: 'lamb',
    rarity: 'uncommon',
    satiety: 13,
    flavorText: 'A habit-forming aroma — your design ideas get habit-forming too.',
    effectLabel: 'Inspiration +2',
  },
  {
    id: 'queijo',
    nameJa: '焼きチーズ',
    nameEn: 'Grilled Cheese',
    category: 'side',
    rarity: 'rare',
    satiety: 6,
    flavorText: 'Happiness up. Error messages a little more forgivable.',
    effectLabel: 'Happiness +3',
  },
  {
    id: 'abacaxi',
    nameJa: '焼きパイナップル',
    nameEn: 'Grilled Pineapple',
    category: 'side',
    rarity: 'rare',
    satiety: 5,
    flavorText: 'Sweetness makes that stack trace easier to forgive.',
    effectLabel: 'Debug resistance +2',
  },
];
